# Use postgres/postgres user/password credentials
services:
  db:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
